### ISSUE TITLE
Swift 2.0 syntax error 

### ISSUE THREAD

**Issue by hooman96** [entotsu/PullToBounce#7]
It seems that swift 2 does not accept the '#' syntax for the function arguments.

This can cause compiling error.

**Comment by desduvauchelle** [comment]
+1

**Comment by silentred** [comment]
+1

**Comment by takuoka** [comment]
+1

**Comment by yoavlt** [comment]
+1

**Comment by darvs** [comment]
I just built the sample app with Xcode 7.1 and did not have this problem.

I think this issue has been fixed by @schickling in https://github.com/entotsu/PullToBounce/commit/7a14480e5ffda86652dd3337a2cd3222c6b2fbda almost 2 months ago.

If you are having this issue, are you using one of the releases (0.0.2 or 0.0.3)? If you are, try to checkout the latest master branch instead and see if that fixes your problem.

**Comment by takuoka** [comment]
Wow, now I append a new tag (0.0.3) to latest commit, and push it to cocoapods. :+1:

**Comment by antonyjamese** [comment]
I have tried with xcode7.3 and Xcode 8.1 still so many compiling error persists.
